<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="0" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-09-21T11:10:03 IST" name="SuiteInsta" finished-at="2022-09-21T11:10:24 IST" duration-ms="20755">
    <groups>
    </groups>
    <test started-at="2022-09-21T11:10:03 IST" name="Test" finished-at="2022-09-21T11:10:24 IST" duration-ms="20755">
      <class name="instagramautomate.VeriffyHomeTestNg">
        <test-method is-config="true" signature="launchbrowser(java.lang.String)[pri:0, instance:instagramautomate.VeriffyHomeTestNg@6ca8564a]" started-at="2022-09-21T11:10:03 IST" name="launchbrowser" finished-at="2022-09-21T11:10:10 IST" duration-ms="6841" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchbrowser -->
        <test-method is-config="true" signature="createPOMObjects()[pri:0, instance:instagramautomate.VeriffyHomeTestNg@6ca8564a]" started-at="2022-09-21T11:10:10 IST" name="createPOMObjects" finished-at="2022-09-21T11:10:10 IST" duration-ms="37" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPOMObjects -->
        <test-method is-config="true" signature="opentheLoginpage()[pri:0, instance:instagramautomate.VeriffyHomeTestNg@6ca8564a]" started-at="2022-09-21T11:10:10 IST" name="opentheLoginpage" finished-at="2022-09-21T11:10:24 IST" duration-ms="13816" status="FAIL">
          <exception class="java.io.FileNotFoundException">
            <message>
              <![CDATA[C:\Users\ADVIKA\OneDrive\Documents\file1.xlsx (The process cannot access the file because it is being used by another process)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.FileNotFoundException: C:\Users\ADVIKA\OneDrive\Documents\file1.xlsx (The process cannot access the file because it is being used by another process)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at utils.Utility.getdatafromsheet(Utility.java:28)
at instagramautomate.VeriffyHomeTestNg.opentheLoginpage(VeriffyHomeTestNg.java:76)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:527)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.FileNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- opentheLoginpage -->
        <test-method signature="test1()[pri:0, instance:instagramautomate.VeriffyHomeTestNg@6ca8564a]" started-at="2022-09-21T11:10:24 IST" name="test1" finished-at="2022-09-21T11:10:24 IST" duration-ms="0" status="SKIP">
          <exception class="java.io.FileNotFoundException">
            <message>
              <![CDATA[C:\Users\ADVIKA\OneDrive\Documents\file1.xlsx (The process cannot access the file because it is being used by another process)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.FileNotFoundException: C:\Users\ADVIKA\OneDrive\Documents\file1.xlsx (The process cannot access the file because it is being used by another process)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at utils.Utility.getdatafromsheet(Utility.java:28)
at instagramautomate.VeriffyHomeTestNg.opentheLoginpage(VeriffyHomeTestNg.java:76)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:527)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.FileNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method is-config="true" signature="aftermethod()[pri:0, instance:instagramautomate.VeriffyHomeTestNg@6ca8564a]" started-at="2022-09-21T11:10:24 IST" name="aftermethod" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1663738824219" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method is-config="true" signature="cleanPOMObjects()[pri:0, instance:instagramautomate.VeriffyHomeTestNg@6ca8564a]" started-at="2022-09-21T11:10:24 IST" name="cleanPOMObjects" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1663738824223" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanPOMObjects -->
        <test-method is-config="true" signature="closetheBrowesr()[pri:0, instance:instagramautomate.VeriffyHomeTestNg@6ca8564a]" started-at="2022-09-21T11:10:24 IST" name="closetheBrowesr" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1663738824226" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closetheBrowesr -->
      </class> <!-- instagramautomate.VeriffyHomeTestNg -->
    </test> <!-- Test -->
  </suite> <!-- SuiteInsta -->
</testng-results>
